version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: todolist
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
